accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import (
    SignUpView,
    delete_user,
    user_delete_success
)

app_name = 'accounts'
urlpatterns = [
   path('signup/', SignUpView.as_view(), name='signup'),
   path('delete/', delete_user, name='delete_user'),
   path('delete/success', user_delete_success, name='user_delete_success'),



]


# path('profile/<str:username>', UserProfileDetailView.as_view(), name='user-profile'),
# path('profile/<int:my_id>', profile_detail_view, name="profile-detail"),
    
# https://learndjango.com/tutorials/django-login-and-logout-tutorial

 
 
 
 

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import HomeView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'home'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('', include('user_profile.urls')),
    path('sets/', include('set.urls')),
    path('flashcards/', include('flashcard.urls')),
]


urlpatterns += staticfiles_urlpatterns()

'''
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
'''

set/urls.py
from django.contrib import admin
from django.urls import path
from set.views import (
    set_create_view,
    set_detail_view,
    set_edit_view,
    set_delete_view,
    list_all_sets,
    set_study_view
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'sets' # namespace of app's urls, to not mix up with main urls
urlpatterns = [
    path('', list_all_sets, name='list_sets'),
    path('create/', set_create_view, name='set_create'),
    path('<int:set_id>', set_detail_view, name='set_detail'),
    path('<int:set_id>/edit/', set_edit_view, name='set_edit'),
    path('<int:set_id>/delete/', set_delete_view, name='set_delete'),
    path('<int:set_id>/study/', set_study_view, name='set_study'),

  
]

urlpatterns += staticfiles_urlpatterns()

user_profile/urls.py
from django.contrib import admin
from django.urls import path
from user_profile.views import (
    profile_detail_view,

)

app_name = 'user_profiles'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', profile_detail_view, name="user-profile"),
   
   
]

home/views.py
from django.views.generic import (
    TemplateView
)




class HomeView(TemplateView):
    template_name = "home.html"

home/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Flashcards</title>
        {% load static %}
        <link rel="stylesheet" href="{% static '/home/base.css' %}" />

        {% block link_style %}

        {% endblock %}
    </head>
    <body>
        {% include 'nav_bar.html' %}
       

        {% block main_content %}
            replace 
        {%endblock %}
    </body>
</html>

home/templates/home.html
{% extends 'base.html' %}






{% block main_content %}
<div class="title_header">
    <h1>Welcome To Flashcards</h1>
    <p>Learn anything by creating your own flashcards.</p>   
    {% if request.user.is_authenticated %}
        <a href="{% url 'user_profiles:user-profile' %}" id="signup_header">My Profile: {{ request.user.username }}</a>
    {% else %}
        <a href= "{% url 'accounts:signup' %}" id="signup_header">Sign-Up</a>
    {% endif %} 
   
</div>



<div class="info_block_wrap">
    <div id="block1" class="info_block">
        <h3>Explore Various Subjects</h3>
        <p>Find flashcard sets from a variety of subjects.</p>    
    </div>
    
    <div id="block2" class="info_block">
        <h3>Explore Various Subjects</h3>
        <p>Find flashcard sets from a variety of subjects.</p>    
    </div>
    
    <div id="block3" class="info_block">
        <h3>Explore Various Subjects</h3>
        <p>Find flashcard sets from a variety of subjects.</p>    
    </div>
</div>



{% endblock main_content %}

home/templates/nav_bar.html
<div class="navigation">
    <div id="home">
        <a href="{% url 'home' %}">Home</a> 
    </div>
    {% if request.user.is_authenticated %}
    <div id="my_sets">
        <a href="{% url 'sets:list_sets' %}">My Sets</a>
    </div>
    <div id="my_profile">
        <a href="{% url 'user_profiles:user-profile' %}">My Profile: {{ request.user.username }}</a>
    </div>
    {% else %}
    <div id="login_navbar">
        <a href="{% url 'login' %}">Log-in</a>
    </div>
    <div id="signup_navbar">
        <a href="{% url 'accounts:signup' %}">Sign-up</a>
    </div>
    {% endif %}
</div>