home/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import HomeView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'home'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('', include('user_profile.urls')),
    path('sets/', include('set.urls')),
    path('flashcards/', include('flashcard.urls')),
]


urlpatterns += staticfiles_urlpatterns()

'''
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
'''

set/urls.py
from django.contrib import admin
from django.urls import path
from set.views import (
    set_create_view,
    set_detail_view,
    set_edit_view,
    set_delete_view,
    list_all_sets,
    set_study_view
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'sets' # namespace of app's urls, to not mix up with main urls
urlpatterns = [
    path('', list_all_sets, name='list_sets'),
    path('create/', set_create_view, name='set_create'),
    path('<int:set_id>', set_detail_view, name='set_detail'),
    path('<int:set_id>/edit/', set_edit_view, name='set_edit'),
    path('<int:set_id>/delete/', set_delete_view, name='set_delete'),
    path('<int:set_id>/study/', set_study_view, name='set_study'),

  
]

urlpatterns += staticfiles_urlpatterns()

set/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Set(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    last_modified = models.DateTimeField()
    date_created = models.DateField(auto_now_add=True)
    last_studied = models.DateTimeField(null=True)
    is_private = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("sets:set_detail", kwargs={"set_id": self.id})

set/forms.py
from django import forms





class CreateSetForm(forms.Form):
    name = forms.CharField(max_length=100, label='',
                                     widget=forms.TextInput(
                                         attrs={
                                             'placeholder': 'Enter Set Name'
                                             }))
    
    is_private = forms.BooleanField(initial=False, required=False)
    
    def __init__(self,*args,**kwargs):
        self.name = kwargs.pop('name', None)   
        super(CreateSetForm,self).__init__(*args,**kwargs)
        self.fields['name'].initial = self.name
        

    def clean(self):
        cleaned_data = super(CreateSetForm, self).clean()
        name = cleaned_data.get('name')
        if not name:
            raise forms.ValidationError('You have to write something!')




class SetFlashcardForm(forms.Form):
    side_one = forms.CharField(max_length=100,
                                 widget=forms.Textarea(
                                    attrs={
                                        "rows": 12,
                                        "cols":75,
                                    }))
    side_two = forms.CharField(max_length=100,
                                 widget=forms.Textarea(
                                    attrs={
                                        "rows": 12,
                                        "cols":75,
                                    }))
    def __init__(self,*args,**kwargs):
        self.set = kwargs.pop('set', None)
        self.side_one = kwargs.pop('side_one', None)
        self.side_two = kwargs.pop('side_two', None)  
        super(SetFlashcardForm,self).__init__(*args,**kwargs)
        self.empty_permitted = False
        self.fields['side_one'].initial = self.side_one
        self.fields['side_two'].initial = self.side_two
        

    def clean(self):
        cleaned_data = super(SetFlashcardForm, self).clean()





class SortSetForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.set_initial = kwargs.pop('set_initial', "Last Modified")
        super().__init__(*args, **kwargs)
        self.fields['sort_by'].widget.attrs.update({'class': 'submit'})
        self.fields['sort_by'].initial = self.set_initial

    CREATED_ON = "Created On"
    LAST_MODIFIED = "Last Modified"
    ALPHABETICAL = "Alphabetical"
    LAST_STUDIED = "Recently Studied"
    

    sort_by_choices =( 
        ( LAST_MODIFIED, "Last Modified"), 
        ( CREATED_ON, "Created On"), 
        ( ALPHABETICAL, "Alphabetical"), 
        ( LAST_STUDIED, "Recently Studied")
    ) 
    
    sort_by = forms.ChoiceField( choices=sort_by_choices)


   

   

set/views.py
from django.shortcuts import render, get_object_or_404, redirect
from flashcard.models import Flashcard
from flashcard.views import flashcard_list_view
from flashcard.forms import  FlashcardForm2
from django.forms import modelformset_factory , inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.utils.timezone import activate
from datetime import datetime, timezone

# Create your views here.
from .models import Set
from .forms import (
    CreateSetForm,
    SortSetForm
)


def set_study_view(request, set_id):
    my_set = get_object_or_404(Set, id =set_id)
    flashcard_list = Flashcard.objects.filter(set=my_set)
    # time_zone = request.POST.get('timezone', '')
    # activate(timezone=time_zone) 


    StarFlashcardFormset = modelformset_factory(Flashcard, fields=('star',))  # min_num=flashcard_count
    star_formset = StarFlashcardFormset(request.POST or None, queryset=flashcard_list)


    my_set.last_studied = datetime.now(timezone.utc)
    my_set.save()
    if request.method == 'POST':
        if star_formset.is_valid():

            star_formset.save()
            print("\n\nstar formset valid")
        else:
            print("\n\nstar formset invalid")
            print(str(star_formset.errors))
    

    flashcard_list_view(request)
    context ={
        "my_set" : my_set,
        'flashcard_list' : flashcard_list,
        "star_formset" : star_formset
    }
    return render(request, "set_study.html", context)


@login_required
def set_create_view(request):
    set_form = CreateSetForm(request.POST or None )
    FlashcardFormSet = inlineformset_factory(Set, Flashcard,form = FlashcardForm2,
            fields=('side_one', 'side_two',), extra=3)
     
    formset = FlashcardFormSet()

    if request.method == 'POST':
        if set_form.is_valid():
            set_name = set_form.cleaned_data['name']
            set = Set(user=request.user, name=set_name) 
            time_zone = request.POST.get('timezone', '')
            activate(timezone=time_zone) 
            set.last_modified = datetime.now()
            set.save()
            
            formset = FlashcardFormSet(request.POST, instance=set)

            if formset.is_valid():
                formset.save()
                return redirect(set.get_absolute_url())

    else:
        print("\n\nform is not valid")

       

    context = {
        'formset': formset,
        'set_form': set_form
    }
    return render(request, "set_create.html", context)
    
    
@login_required
def set_edit_view(request, set_id):
    my_set = get_object_or_404(Set, id=set_id, user=request.user)
    set_form = CreateSetForm(request.POST or None, name=my_set.name)
    FlashcardFormSet = inlineformset_factory(Set, Flashcard,form = FlashcardForm2,
        fields=('side_one', 'side_two',), extra=1)
    formset = FlashcardFormSet(instance=my_set)

    if request.method == 'POST':
        if set_form.is_valid():
            set_name = set_form.cleaned_data['name']
            # time_zone = request.POST.get('timezone', '')
            # activate(timezone=time_zone) 
            my_set.name = set_name
            my_set.last_modified = datetime.now(timezone.utc)
            my_set.save()
            formset = FlashcardFormSet(request.POST, instance=my_set)

            if formset.is_valid():
                formset.save()
                return redirect(my_set.get_absolute_url())

    else:
        print("\n\nform is not valid")

       

    context = {
        'formset': formset,
        'set_form': set_form
    }
    return render(request, "set_edit.html", context)




@login_required
def set_delete_view(request, set_id):
    my_set = get_object_or_404(Set, id=set_id, user=request.user)
    if request.method == "POST":
        Set.objects.filter(id=set_id).delete()
        return redirect('sets:list_sets')
    context ={
        'set_name' : my_set.name
    }
    return render(request, "set_delete.html", context)


def set_detail_view(request, set_id):
    my_set = get_object_or_404(Set, id =set_id)
    flashcard_list = Flashcard.objects.filter(set=my_set)

    flashcard_list_view(request)
    context ={
        "my_set" : my_set,
        'flashcard_list' : flashcard_list
    }
    return render(request, "set_detail.html", context)


@login_required
def list_all_sets(request):
    CREATED_ON = "Created On"
    LAST_MODIFIED = "Last Modified"
    ALPHABETICAL = "Alphabetical"
    LAST_STUDIED = "Recently Studied"
    


    sort_form = SortSetForm()
    queryset = Set.objects.filter(user=request.user).order_by('-last_modified')
    

    if request.POST: 
        sort_by = request.POST.get('sort_by', LAST_MODIFIED)
        print(sort_by)   
        if sort_by == CREATED_ON:
            queryset = Set.objects.filter(user=request.user).order_by('-date_created') 
        if sort_by == LAST_MODIFIED:
            queryset = Set.objects.filter(user=request.user).order_by('-last_modified') 
        if sort_by == ALPHABETICAL:
            queryset = Set.objects.filter(user=request.user).order_by('name')
        if sort_by == LAST_STUDIED:
            queryset = Set.objects.filter(user=request.user).order_by('-last_studied')
            
        sort_form = SortSetForm(set_initial=sort_by)
        


    context ={    
        'set_list' : queryset,
        'sort_form' : sort_form
    }
   
    return render(request, "set_list.html", context)

set/templates/set_create.html
{% extends 'base.html' %}


{% block link_style %}

{% load static %}
<link rel="stylesheet" href="{% static '/set/set.css' %}" />

{%endblock link_style %}

{% block main_content %}

<script>
    

    window.onload = function deleteDuplicateHeaders(){
        const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
        console.log(tz);

        var timezone_input = document.createElement("input");
        timezone_input.type = "hidden";
        timezone_input.name = "timezone"; 
        timezone_input.value = tz; 


        var create_set_form = document.getElementById("create_set_form");
        var num_forms = document.getElementById("id_flashcard_set-TOTAL_FORMS");
        var intial_forms = document.getElementById("id_flashcard_set-INITIAL_FORMS"); 
        var min_forms = document.getElementById("id_flashcard_set-MIN_NUM_FORMS"); 
        var max_forms = document.getElementById("id_flashcard_set-MAX_NUM_FORMS");  

        if(num_forms!=null && intial_forms!=null
                 && min_forms !=null && max_forms !=null){
            create_set_form.removeChild(num_forms); 
            create_set_form.removeChild(intial_forms); 
            create_set_form.removeChild(min_forms); 
            create_set_form.removeChild(max_forms); 
        }

        var num_forms2 = document.getElementById("id_flashcard_set-TOTAL_FORMS");
        create_set_form.insertBefore(timezone_input, num_forms2);


        

        var add_btn = document.getElementById("add_btn"); 

        
        var arrOfPara = create_set_form.getElementsByTagName("p");

        var flashcard_container = document.createElement("div");
        flashcard_container.setAttribute("class",  "flashcard_container");

        for(var i = 1; i < arrOfPara.length; i++){

            var para = create_set_form.removeChild(arrOfPara[2]);
            if ( (i-1)%3 == 0){
                para.setAttribute("class",  "side_two");
                flashcard_container.appendChild(para);
            }
            if ( (i-2)%3 == 0){ 
                para.setAttribute("class",  "side_one");
                flashcard_container.appendChild(para);
            }
            if(  i%3 == 0  ){
                para.setAttribute("class",  "delete_checkbox");
                flashcard_container.appendChild(para);

                console.log("in if"); 
                create_set_form.insertBefore(flashcard_container, add_btn); 
                flashcard_container = document.createElement("div");
                flashcard_container.setAttribute("class",  "flashcard_container"); 
            } 
        }
        var para = create_set_form.removeChild(arrOfPara[2]);
        para.setAttribute("class",  "delete_checkbox"); 
        flashcard_container.appendChild(para); 
        create_set_form.insertBefore(flashcard_container, add_btn); 
        
    }
    
    function addFlashCardField(){
        
        var create_set_form = document.getElementById("create_set_form");
        var total_forms = document.getElementById("id_flashcard_set-TOTAL_FORMS"); 
        total_forms.value = ++total_forms.value; 
        form_index = total_forms.value -1; 
  

        var add_btn = document.getElementById("add_btn"); 
 
        var flashcard_container = document.createElement("div");
        flashcard_container.setAttribute("class",  "flashcard_container");
        var paragraph_one = document.createElement("p");
        paragraph_one.setAttribute("class",  "side_one"); 

        var side_one = document.createElement("textarea");
        side_one.name = `flashcard_set-${form_index}-side_one`;
        side_one.cols = "55"; 
        side_one.rows = "6"; 
        side_one.id = `id_flashcard_set-${form_index}-side_one`;
        side_one.placeholder = "Enter Term";  
        paragraph_one.appendChild(side_one); 

        

        var paragraph_two = document.createElement("p");
        paragraph_two.setAttribute("class",  "side_two");
        var side_two = document.createElement("textarea");
        side_two.name = `flashcard_set-${form_index}-side_two`;
        side_two.cols = "55"; 
        side_two.rows = "6"; 
        side_two.id = `id_flashcard_set-${form_index}-side_two`; 
        side_two.placeholder = "Enter Definition"; 
        paragraph_two.appendChild(side_two);  



        var paragraph_three = document.createElement("p");
        paragraph_three.setAttribute("class",  "delete_checkbox");
        var label_three = document.createElement("label");
        label_three.htmlFor = `id_flashcard_set-${form_index}-DELETE`;
        label_three.innerHTML = "Delete: "; 
        paragraph_three.appendChild(label_three); 
        var check_box = document.createElement("input");
        check_box.type = "checkbox";
        check_box.name = `flashcard_set-${form_index}-DELETE`; 
        check_box.id = `id_flashcard_set-${form_index}-DELETE`; 
        paragraph_three.appendChild(check_box); 
        var hidden_one = document.createElement("input"); 
        hidden_one.type = "hidden"; 
        hidden_one.name = `flashcard_set-${form_index}-id`; 
        hidden_one.id = `id_flashcard_set-${form_index}-id`; 
        paragraph_three.appendChild(hidden_one); 
        var hidden_two = document.createElement("input"); 
        hidden_two.type = "hidden"; 
        hidden_two.name = `flashcard_set-${form_index}-set`; 
        hidden_two.id = `id_flashcard_set-${form_index}-set`; 
        paragraph_three.appendChild(hidden_two); 
        
        
        flashcard_container.appendChild(paragraph_one);  
        flashcard_container.appendChild(paragraph_two);  
        flashcard_container.appendChild(paragraph_three); 
        create_set_form.insertBefore(flashcard_container, add_btn);  
    }

  
</script>




<form id = "create_set_form" action='.' method='POST' >{% csrf_token %}
    <h1>Create a new set</h1>
    {{ set_form.as_p }}
    <hr>
    <br>
    {{ formset.management_form}}
    {{ formset.as_p }}
    

    <input id="add_btn" type="button" value="add flashcard" onclick="addFlashCardField()"><br>
    <input class="form_button" id="create_btn" type='submit' value='Create'/> 
</form> 



{%endblock main_content %}

set/templates/set_delete.html
{% extends 'base.html' %}



{% block link_style %}

{% load static %}

<link rel="stylesheet" href="{% static '/set/set.css' %}" />

{%endblock link_style %}
{% block main_content %}

<div class="main_content">
    <h1>Delete Set</h1>
    <hr>
    <form action='.' method='POST'> {% csrf_token %}
        <h3>Are you sure you want to delete "{{ set_name }}" ? </h3>
        <input class="form_button" type='submit' value='Yes'/> 
    </form>
</div>


{% endblock main_content %}

set/templates/set_detail.html
{% extends 'base.html' %}



{% block link_style %}

{% load static %}
<link rel="stylesheet" href="{% static '/set/set.css' %}" />

{%endblock link_style %}




{% block main_content %}
<div class="main_content">
    <h1>{{ my_set.name }}</h1>
    <h1> Created By: {{ my_set.user }} </h1>

<a class = "action_button" href="{% url 'sets:set_edit' set_id=my_set.id %}" >Edit Set</a>
<a class= "action_button" href="{% url 'sets:set_delete' set_id=my_set.id %}" >Delete Set</a>
<a class= "action_button" href="{% url 'sets:set_study' set_id=my_set.id %}" >Study Set</a>

<hr>
<br>

{% include 'flashcard_list.html' %} <br>

</div>






{%endblock main_content %}

set/templates/set_list.html
{% extends 'base.html' %}


{% block link_style %}

{% load static %}
<link rel="stylesheet" href="{% static '/set/set.css' %}" />

{%endblock link_style %}




{% block main_content %}
<div class="main_content">
    <h1>My Flashcard Sets</h1>
    <a class= "action_button" id="create_set_link" href="{% url 'sets:set_create' %}" >Create Set</a>
    <hr>
    <br>
  
    <form id = "sort_form" action='.' method='POST' >{% csrf_token %}
       
        {{ sort_form.as_p }}
        
    </form> 

    
    {% for instance in set_list %}          
        <a  class="set_card" href='{{instance.get_absolute_url}}'>  
            <strong>{{ instance.name}} </strong> <br>
            <small>created on: {{instance.date_created}} </small><br>
            <small>last modified: {{instance.last_modified }} </small><br>
            <small>last studied: {{instance.last_studied }} </small>
        </a> <br>
        <br>
       
    {% endfor %}
</div>

<script>

    const myForm = document.getElementById("sort_form"); 
    document.querySelector('select.submit').addEventListener("change", function(){

        myForm.submit();

    });


  
</script>

{% endblock main_content %}

set/templates/set_study.html
{% extends 'base.html' %}




{% block link_style %}

{% load static %}
<link rel="stylesheet" href="{% static '/set/set.css' %}" />

{%endblock link_style %}




{% block main_content %}
<div class="main_content"> 
    <h1>{{ my_set.name }}</h1>

    <hr>
    <br>
    <input id="timezone" type="hidden" name="timezone" value="">



    <form id="star_form" style="display: none;" action='.' method='POST' >{% csrf_token %}
        {{ star_formset.management_form}}
        {{ star_formset.as_p }}
        <!-- <input type="submit"> -->
        <!-- <input class="form_button" id="create_btn" type='submit' value='Star'/>  -->
    </form> 

    <div class="slideshow_container">
        {% for instance in flashcard_list %}
        
        
        <div class="flashcard" >
            <div class="flashcard_inner" onclick="flipFlashcard()">
                <div class="flashcard_side_one">

              
                        <button style="z-index: 3;" class="id_form-{{ forloop.counter0 }}-star" onclick="starFlashcard(this)">
                            {% if instance.star %}
                                Unstar
                            {% else %}
                                Star
                            {% endif %}
                        </button>
                  
                   
                    <p ><strong>Term: </strong> {{ instance.side_one }}</p>
                    
                    
                </div>
               <div class="flashcard_side_two">
                  
                        <button style="z-index: 3;" class="id_form-{{ forloop.counter0 }}-star" onclick="starFlashcard(this)" >
                            {% if instance.star %}
                                Unstar
                            {% else %}
                                Star
                            {% endif %}
                        </button>
                   
                   
                    <p ><strong>Definition: </strong> {{ instance.side_two }}</p>
               </div>
            </div>
        </div>
       
        {% endfor %}
      
        <br>
        
       
        <div class="arrow_container">
            <a class="arrow" onclick="plusSlides(-1)">&#10094;</a>
            <a class="arrow" onclick="plusSlides(1)">&#10095;</a>
            <!-- <a class="arrow" onclick="flipFlashcard()">Flip</a> -->
        </div>
        
    </div>

    <script>
        var slideIndex = 1;
        var isSideOne = true;
        var moveRight = true; 
        var slides = document.getElementsByClassName("flashcard");
        var flashcard_inner = document.getElementsByClassName("flashcard_inner");
        var flashcardSideOne = document.getElementsByClassName("flashcard_side_one"); 
        var flashcardSideTwo= document.getElementsByClassName("flashcard_side_two"); 

        const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
        console.log(tz);
        var timezone_input = document.getElementById("timezone");
        timezone_input.value = tz;


        showSlides(slideIndex);

              


        function starFlashcard(button){
            event.stopPropagation();
            console.log("star button clicked!"); 
            var buttonClass = button.getAttribute('class');
             
            console.log(buttonClass); 
            var starCheckbox = document.getElementById(buttonClass); 
            starCheckbox.checked = !starCheckbox.checked;
            
            document.getElementById("star_form").submit();  
        }

        function flipFlashcard(){
                if(isSideOne){
                    flashcard_inner[slideIndex -1].style.transform = "rotateX(180deg)"; 
                }
                else{
                    flashcard_inner[slideIndex -1].style.transform = "none"; 
                }
                isSideOne = !isSideOne; 
        }

     
  

        function plusSlides(n) {
            if(slides.length == 0){
                // no flashcards in the set
                return;
            }
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            // slideFlashcardLeft(); 
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            if(slides.length == 0){
                // no flashcards in the set
                var noFlashCardMessage = document.createElement('p');
                noFlashCardMessage.innerText = "No flashcard has been added to this set. To add flashcards, edit the set.";
                var slideShowContainer = document.getElementsByClassName("slideshow_container");
                slideShowContainer[0].appendChild(noFlashCardMessage); 
                var arrowButtons = document.getElementsByClassName("arrow");
                for(var i = 0; i < arrowButtons.length; i++){
                    arrowButtons[i].style.display = "none"; 
                }
                
                var editSetLink = document.createElement('a');
                editSetLink.setAttribute("class",  "action_button");
                editSetLink.href = "{% url 'sets:set_edit' set_id=my_set.id %}"; 
                editSetLink.innerText = "Edit Set"; 
                slideShowContainer[0].appendChild(editSetLink); 
                return;
            }
            var i;
            if (n > slides.length) {
                slideIndex = 1;
            }
            if (n < 1) {
                slideIndex = slides.length;
            }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
                flashcardSideTwo[i].style.display = "none"; 
            }
            slides[slideIndex - 1].style.display = "block";
            flashcardSideTwo[slideIndex -1].style.display = "block"; 
            
        }
        // put flipflashcard function here
        function slideFlashcardLeft(){
            slides[slideIndex -1].style.transform = "rotateY(-70deg)"; 
            flashcard_inner[slideIndex -1].style.transform = "rotateY(-70deg)"; 
            flashcardSideOne[slideIndex -1].style.transform = "rotateY(180deg)";  

        }
        function slideFlashcardRight(){
            slides[slideIndex -1].style.transform = "rotateY(70deg)"; 
            flashcard_inner[slideIndex -1].style.transform = "rotateY(70deg)"; 
            flashcardSideOne[slideIndex -1].style.transform = "rotateY(180deg)"; 

        }



    window.onload = function getTimezone(){
        var star_form = document.getElementById("star_form");
        const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
        console.log(tz);

        var timezone_input = document.createElement("input");
        timezone_input.type = "hidden";
        timezone_input.name = "timezone"; 
        timezone_input.value = tz; 


        var num_forms2 = document.getElementById("id_flashcard_set-TOTAL_FORMS");
        star_form.insertBefore(timezone_input, num_forms2);
        
    }

    
    </script>




    {%endblock main_content %}